---
title: "Técnicas Avanzadas de Estadística"
author: "[Javier Cara](https://www.javiercara.com/)"
date: "curso 2019-20"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
---

<br>

***

# Contenido

## Regresión lineal

1. Modelo de regresión lineal
    a. [Modelo matemático y su estimación](lm_estimacion.html)
    b. [Estimación del modelo de regresión lineal con R](lm_estimacionR.html)
    c. [Regresión lineal con términos de interacción](lm_interaccion.html)
    d. [Fórmulas y expresiones en el modelo de regresión](lm_formulas.html)
    e. [Regresión lineal con variables cualitativas](lm_cualitativas.html)
2. Inferencia en el modelo de regresión lineal
    a. [Distribuciones en el muestreo](lm_inferencia_muestreo.html)
    b. [Intervalos de confianza](lm_inferencia_intervalos.html)
    c. [Contrastes de hipótesis](lm_inferencia_contrastes.html)
    d. [Bootstrap](lm_inferencia_bootstrap.html)
3. Aplicaciones del modelo de regresión lineal
    a. [Cálculo de predicciones](lm_aplicaciones_prediccion.html)
    b. [Explicación de las relaciones entre variables](lm_aplicaciones_explicacion.html)
4. Diagnosis
    a. [Análisis de los residuos del modelo](lm_diagnosis.html)
5. Ejemplo
    a. [Ejemplo](lm_ejemplo1.html)
6. Extensiones del modelo lineal
    a. [Regresores polinómicos](lm_extensiones_polinomios.html)
    b. [Splines de regresión](lm_extensiones_splines.html)
    c. [Modelos aditivos](lm_extensiones_modelosAditivos.html)
    d. [Regresión local](lm_extensiones_regresionLocal.html) (No entra en el examen)
7. Validación cruzada.
    a. [Validación cruzada](lm_validacion_cruzada.html)
8. Selección de variables
    a. [Selección de variables](lm_seleccion_variables.html)
    
## Árboles de regresión y clasificación

1. Árboles de regresión
    a. Introducción
    b. [Estimación](tree_regresion.html)
    c. [Random Forest](tree_RandomForest.html)
    d. [Boosting](tree_boosting.html) (No entra en el examen)
2. Árboles de clasificación
    a. [Árboles de clasificación](tree_clasificacion.html)


# Bibliografía

Los libros utilizados en la redacción de estos apuntes han sido, fundamentalmente:

- **[Faraway2014]** Linear models with R. Julian J. Faraway. Chapman and Hall/CRC. Edicion 2, 2014.
- **[Gelman2007]** Data Analysis Using Regression and Multilevel/Hierarchical Models. Andrew Gelman, Jennifer Hill. Cambridge University Press. 2007.
- **[James2017]** An Introduction to Statistical Learning: with Applications in R. Gareth James, Daniela Witten, Trevor Hastie and Rob Tibshirani. Springer, 2017.
- **[Montgomery2013]** Introduction to Linear Regression Analysis. Douglas Montgomery, Elisabeth Peck, Geofrey Vining . Editorial Wiley-Blackwell, Edicion 5, 2013.
- **[Peña2010]** Regresión y diseño de experimentos. Daniel Peña. Alianza Editorial, 2010.
- **[Sheather2009]** A modern approach to regression with R. Simon J. Sheather. Springer tests in Statistics, 2009.

# Archivos de datos

- [Advertising.csv](datos/Advertising.csv). Mas información en [James2017].
- [cerezos.txt](datos/cerezos.txt)
- [coches.txt](datos/coches.txt)
- [kidiq.csv](datos/kidiq.csv). Mas información en [Gelman2007].
- [Hitters.csv](datos/Hitters.csv). Mas información en [James2017].
- [Wage.csv](datos/Wage.csv). Mas información en [James2017].

# Funciones

- [cross_val_pos()](funciones/cross_val_pos.R).
- [MSE()](funciones/MSE.R)
- [predict.regsubsets()](funciones/regsubsets_predict.R).



<br>